-- ============================================================================
-- COGNIZANT DIGITAL NURTURE 5.0 - MODULE 3: DATABASE INTEGRATION
-- HANDS-ON 4: PERFORMANCE TUNING, INDEXES & THE N+1 QUERY PROBLEM
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. EXPLAIN AND EXPLAIN ANALYZE
-- ----------------------------------------------------------------------------

-- Before indexing, let's analyze how a query is executed.
-- EXPLAIN shows the execution plan generated by the optimizer without running the query.
-- EXPLAIN ANALYZE executes the query and shows actual execution times, loop counts, and costs.

-- Query A: Scanning students filtering by department_id and enrollment_year
-- (PostgreSQL Syntax - For MySQL, write: EXPLAIN FORMAT=TREE SELECT ...)
EXPLAIN
SELECT * 
FROM Students 
WHERE department_id = 1 AND enrollment_year = 2024;

-- Query B: Running and obtaining execution stats
-- (PostgreSQL Syntax - For MySQL, write: EXPLAIN ANALYZE SELECT ...)
EXPLAIN ANALYZE
SELECT * 
FROM Students 
WHERE department_id = 1 AND enrollment_year = 2024;

-- Query C: Complex Multi-Join execution analysis
EXPLAIN ANALYZE
SELECT s.first_name, s.last_name, d.dept_name, c.course_name, e.grade
FROM Students s
INNER JOIN Departments d ON s.department_id = d.department_id
INNER JOIN Enrollments e ON s.student_id = e.student_id
INNER JOIN Courses c ON e.course_id = c.course_id
WHERE s.enrollment_year = 2024 AND d.dept_name = 'Computer Science';

-- ----------------------------------------------------------------------------
-- 2. INDEX CREATION (TUNING)
-- ----------------------------------------------------------------------------

-- --- INDEX A: UNIQUE INDEX ---
-- Unique indexes ensure that no two rows can have the same value for the indexed columns.
-- (Note: Primary Keys and UNIQUE constraints automatically create unique indexes).
-- Let's create an explicit unique index on the course code if not already created.
CREATE UNIQUE INDEX idx_courses_course_code ON Courses(course_code);

-- --- INDEX B: COMPOSITE INDEX ---
-- A composite index (multi-column index) optimizes queries that filter on multiple fields.
-- The order of columns matters: put the column with higher cardinality (or the one used in equality filters) first.
-- This optimizes queries filtering by department_id AND enrollment_year.
CREATE INDEX idx_students_dept_year ON Students(department_id, enrollment_year);

-- Test the performance improvement with EXPLAIN ANALYZE again.
-- The optimizer should now perform an "Index Scan" or "Bitmap Index Scan" instead of a "Seq Scan" (Sequential scan).
EXPLAIN ANALYZE
SELECT * 
FROM Students 
WHERE department_id = 1 AND enrollment_year = 2024;

-- --- INDEX C: PARTIAL INDEX (DIALECT SPECIFIC) ---
-- A partial index is built over a subset of a table defined by a conditional expression.
-- It reduces index size, speeds up index maintenance, and accelerates specific queries.
-- PostgreSQL supports Partial Indexes out of the box. 
-- In MySQL (prior to 8.0), this is not directly supported, but functional indexes can achieve similar results.
CREATE INDEX idx_students_enrolled_2025 ON Students(student_id) 
WHERE enrollment_year = 2025;

-- Test the partial index usage
EXPLAIN ANALYZE
SELECT student_id 
FROM Students 
WHERE enrollment_year = 2025 AND student_id = 103;

-- ----------------------------------------------------------------------------
-- 3. PERFORMANCE COMPARISON EXPLANATION
-- ----------------------------------------------------------------------------
/*
PERFORMANCE COMPARISON (Sequential Scan vs. Index Scan):

1. SEQUENTIAL SCAN (Seq Scan / Table Scan):
   - The database engine reads every page of the table from disk to find matching rows.
   - Time Complexity: O(N) where N is the total number of rows.
   - Efficient for: Very small tables (where loading index blocks is slower than loading the table) 
     or queries returning more than 20-30% of the entire table rows.

2. INDEX SCAN (B-Tree Index Scan):
   - The database searches the balanced B-Tree index structure to locate pointer addresses (TIDs).
   - Time Complexity: O(log N).
   - Efficient for: Queries returning a small percentage of rows, point lookups (e.g., student_id = 101), 
     and columns used in JOINs.

3. WRITE IMPACT:
   - Indexes accelerate SELECT read operations but introduce overhead on INSERT, UPDATE, and DELETE.
   - For every insert/update, the database must write to the table AND re-balance the B-Tree indexes.
   - Rule of Thumb: Index columns used frequently in WHERE clauses, JOIN conditions, and ORDER BY, 
     but avoid over-indexing tables with high write frequency.
*/

-- ----------------------------------------------------------------------------
-- 4. THE N+1 QUERY PROBLEM EXPLAINED
-- ----------------------------------------------------------------------------
/*
THE N+1 QUERY PROBLEM:

Definition:
The N+1 query problem occurs when an application retrieves a list of records from a database (1 query)
and then, for each of those records, executes another query (N queries) to fetch related data.
Total queries executed: N + 1.

Scenario:
We want to list all Students and print their Department names.
1. Without Optimization (Lazy Loading):
   - Query 1: SELECT * FROM Students; -- Returns N students (e.g., 100 students).
   - Query 2 to N+1: For each student, run: SELECT * FROM Departments WHERE department_id = ?;
   - Results in 101 database roundtrips! This is highly inefficient, creating network latency bottlenecks.

2. With Optimization (Eager Loading / JOINs):
   - Query 1: SELECT s.*, d.dept_name 
              FROM Students s 
              LEFT JOIN Departments d ON s.department_id = d.department_id;
   - Result: Fetches all students and department details in exactly 1 query!
*/

-- ----------------------------------------------------------------------------
-- 5. PYTHON DEMONSTRATION SCRIPT FOR N+1 PROBLEM (SQLAlchemy)
-- ----------------------------------------------------------------------------
/*
Below is the complete python script demonstrating the difference.
This script creates a local SQLite database, inserts mock data, and executes
both N+1 lazy-loaded queries and optimized joined-loaded queries, comparing 
the query count and execution speed.

To run this demonstration:
1. Copy the code block below into a file named `n1_demo.py` (or execute `python orm/test.py` in the project)
2. Run `python n1_demo.py`

```python
import time
import logging
from sqlalchemy import create_engine, Column, Integer, String, ForeignKey
from sqlalchemy.orm import declarative_base, sessionmaker, relationship, joinedload

# 1. Setup logging to capture SQL queries executed
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("SQLAlchemy")
# We'll count the number of SQL statements emitted
query_count = 0
class QueryCounterHandler(logging.Handler):
    def emit(self, record):
        global query_count
        if "INFO:sqlalchemy.engine.Engine:[raw sql]" in record.getMessage() or "SELECT" in record.getMessage():
            query_count += 1

sql_logger = logging.getLogger("sqlalchemy.engine")
sql_logger.setLevel(logging.INFO)
handler = QueryCounterHandler()
sql_logger.addHandler(handler)

Base = declarative_base()

class Department(Base):
    __tablename__ = 'departments'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    students = relationship("Student", back_populates="department")

class Student(Base):
    __tablename__ = 'students'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    department_id = Column(Integer, ForeignKey('departments.id'))
    department = relationship("Department", back_populates="students")

# Initialize SQLite database in memory for speed
engine = create_engine('sqlite:///:memory:')
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

# Seed database with 50 departments and 100 students
depts = [Department(name=f"Department {i}") for i in range(50)]
session.add_all(depts)
session.commit()

students = []
for i in range(100):
    # Assign student to department
    dept = depts[i % 50]
    students.append(Student(name=f"Student {i}", department=dept))
session.add_all(students)
session.commit()

session.clear() # Clear session to force reloading from database

# --- SCENARIO 1: DEMONSTRATING N+1 PROBLEM (LAZY LOADING) ---
print("\n=== SCENARIO 1: LAZY LOADING (N+1 PROBLEM) ===")
query_count = 0
start_time = time.perf_counter()

# Fetches students (1 query)
students_lazy = session.query(Student).all()
for student in students_lazy:
    # Accessing department triggers a new SELECT query for each student (N queries)
    dept_name = student.department.name

end_time = time.perf_counter()
lazy_time = (end_time - start_time) * 1000
lazy_queries = query_count
print(f"Lazy Loaded {len(students_lazy)} students.")
print(f"Queries executed: {lazy_queries}")
print(f"Execution time: {lazy_time:.2f} ms")


session.clear() # Clear session to force reloading from database

# --- SCENARIO 2: DEMONSTRATING OPTIMIZED JOIN (EAGER LOADING) ---
print("\n=== SCENARIO 2: EAGER LOADING (JOINEDLOAD - OPTIMIZED) ===")
query_count = 0
start_time = time.perf_counter()

# Fetches students and their departments in 1 query using JOIN
students_eager = session.query(Student).options(joinedload(Student.department)).all()
for student in students_eager:
    # Department is already in session, no extra queries triggered
    dept_name = student.department.name

end_time = time.perf_counter()
eager_time = (end_time - start_time) * 1000
eager_queries = query_count
print(f"Eager Loaded {len(students_eager)} students.")
print(f"Queries executed: {eager_queries}")
print(f"Execution time: {eager_time:.2f} ms")

print("\n=== SUMMARY COMPARISON ===")
print(f"Lazy Load Queries: {lazy_queries} | Eager Load Queries: {eager_queries} (Savings: {lazy_queries - eager_queries} queries)")
print(f"Lazy Load Time: {lazy_time:.2f} ms | Eager Load Time: {eager_time:.2f} ms (Speedup: {lazy_time/eager_time:.2f}x)")

session.close()
```
*/
